# Generated by Django 3.0.4 on 2020-04-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereço', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
