# Generated by Django 3.0.5 on 2020-05-04 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereço', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('cpf', models.CharField(max_length=25, unique=True)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Conteudos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.CharField(max_length=200)),
                ('conteudo', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('postador', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('professor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('postador', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
