# Generated by Django 3.0.4 on 2020-04-18 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200417_0105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conteudos',
            new_name='Extras',
        ),
    ]
